language: python
python:
  - "3.7.7"
cache: pip
before_install:
  - sudo apt-get update
  - sudo apt-get install glpk-utils

install:
  - pip install -r requirements-ubuntu-20-04.txt
script:
  - python -m unittest discover tests